# Define website routes in `routes_website.yaml` and admin routes in the `routes_admin.yaml`

product_index:
    path: /api/products
    controller: App\Controller\ProductController::index
    methods: GET

product_create:
    path: /api/products
    controller: App\Controller\ProductController::create
    methods: POST

product_show:
    path: /api/products/{id}
    controller: App\Controller\ProductController::show
    methods: GET

product_update:
    path: /api/products/{id}
    controller: App\Controller\ProductController::update
    methods: PUT

product_delete:
    path: /api/products/{id}
    controller: App\Controller\ProductController::delete
    methods: DELETE
